### ISSUE TITLE
Incorrect tailscale and usb web interface instructions

### ISSUE THREAD

**Issue by rM-self-serve** [Eeems-Org/remarkable.guide#57]
I submitted https://github.com/Eeems-Org/remarkable.guide/pull/49 after user confirmation, but upon configuring tailscale myself I have found that tailscale can only share services running on localhost.

I have proposed a [package](https://github.com/toltec-dev/toltec/pull/840) in toltec that will allow the web interface to be accessed over tailscale. Upon that package being merged, the guide can be updated to include/point to the new instructions.

In the meantime it may be advisable to revert #49.

**Comment by Eeems** [comment]
> In the meantime it may be advisable to revert #49.

As this would remove the anchor that people may be linking to, this would not be the correct solution for the site. Updated content with a workaround to get this to work, or explaining that it's not currently possible would need to be added, or the anchor added to another place on the page.

**Comment by rM-self-serve** [comment]
Would it be advisable to wait for https://github.com/toltec-dev/toltec/pull/840 or shall I open a pull request here stating that the specific section/anchor is under maintenance?

**Comment by Eeems** [comment]
> Would it be advisable to wait for [toltec-dev/toltec#840](https://github.com/toltec-dev/toltec/pull/840) or shall I open a pull request here stating that the specific section/anchor is under maintenance?

Either works for me. It'll be a little while before https://github.com/toltec-dev/toltec/pull/840 gets to stable.

**Comment by Eeems** [comment]
Since the new package is in stable, are you planning on opening a pr to update this?
